### ISSUE TITLE
how to use by content_scripts?

### ISSUE THREAD

**Issue by jojowwbb** [Aniny21/browser-extension-ffmpeg#1]

**Comment by Aniny21** [comment]
@jojowwbb 
The files necessary to run ffmpeg with content_scripts are already set to be loaded in `manifest.json`, so this can be done by simply adding almost the same content as `options.js` to an empty `content.js`.

The following is an example of converting `data/sample_audio.wav` to `sample_audio.mp3` in content_scripts (the converted `sample_audio.mp3` is downloaded each time the page is loaded).

``` javascript
console.log("content.js loaded");

const { createFFmpeg, fetchFile } = FFmpeg;

const ffmpeg = createFFmpeg({
    corePath: chrome.runtime.getURL("lib/ffmpeg-core.js"),
    log: true,
    mainName: 'main'
});

(async () => {
    const inputFileName = 'sample_audio.wav';
    const outputFileName = 'sample_audio.mp3';
    const commandStr = `-i ${inputFileName} -vn -ac 2 -ar 44100 -ab 256k -acodec libmp3lame -f mp3 ${outputFileName}`;
    const inputAudioUrl = chrome.runtime.getURL(`data/${inputFileName}`);

    if (ffmpeg.isLoaded()) {
        await ffmpeg.exit();
    }
    
    await ffmpeg.load();


    ffmpeg.FS('writeFile', inputFileName, await fetchFile(inputAudioUrl));
    await ffmpeg.run(...commandStr.split(' '));

    const data = ffmpeg.FS('readFile', outputFileName);
    const blob = new Blob([data.buffer]);

    // Download file
    const a = document.createElement('a');
    a.href = URL.createObjectURL(blob);
    a.download = outputFileName;
    a.click();
})();

```

**Comment by jojowwbb** [comment]
> @jojowwbb The files necessary to run ffmpeg with content_scripts are already set to be loaded in `manifest.json`, so this can be done by simply adding almost the same content as `options.js` to an empty `content.js`.
> 
> The following is an example of converting `data/sample_audio.wav` to `sample_audio.mp3` in content_scripts (the converted `sample_audio.mp3` is downloaded each time the page is loaded).
> 
> ```js
> console.log("content.js loaded");
> 
> const { createFFmpeg, fetchFile } = FFmpeg;
> 
> const ffmpeg = createFFmpeg({
>     corePath: chrome.runtime.getURL("lib/ffmpeg-core.js"),
>     log: true,
>     mainName: 'main'
> });
> 
> (async () => {
>     const inputFileName = 'sample_audio.wav';
>     const outputFileName = 'sample_audio.mp3';
>     const commandStr = `-i ${inputFileName} -vn -ac 2 -ar 44100 -ab 256k -acodec libmp3lame -f mp3 ${outputFileName}`;
>     const inputAudioUrl = chrome.runtime.getURL(`data/${inputFileName}`);
> 
>     if (ffmpeg.isLoaded()) {
>         await ffmpeg.exit();
>     }
>     
>     await ffmpeg.load();
> 
> 
>     ffmpeg.FS('writeFile', inputFileName, await fetchFile(inputAudioUrl));
>     await ffmpeg.run(...commandStr.split(' '));
> 
>     const data = ffmpeg.FS('readFile', outputFileName);
>     const blob = new Blob([data.buffer]);
> 
>     // Download file
>     const a = document.createElement('a');
>     a.href = URL.createObjectURL(blob);
>     a.download = outputFileName;
>     a.click();
> })();
> ```

I had tried as you,but i got error:
SharedArrayBuffer is not undefined;

**Comment by Aniny21** [comment]
@jojowwbb 
You seem to be importing a file that is not ffmpeg-core.js in this repository.
There are single-threaded and multi-threaded versions of ffmpeg wasm, and the multi-threaded version uses SharedArrayBuffer, which may not work.
